In [1]:
import pandas as pd

# 폭력지수 산출

### 취약점수 + 위해점수 - 경감점수 = 폭력지수

##### 1. 데이터 로드 및 전처리

In [2]:
Vulnerability = pd.read_csv('data/Vulnerability_Indicator_final1.csv')
Hazard=pd.read_csv('data/hazard_indicator.csv')
Reduce = pd.read_csv('data/경감지표.csv',encoding='cp949')

- Vulnerability의 점수 칼럼 이름 수정

In [3]:
Vulnerability = Vulnerability.rename({'score_2nd':'Vul_score'},axis=1)

In [4]:
Vulnerability

                 학교명   자치구  Vul_score
0           국립국악고등학교   강남구       2.67
1             개포고등학교   강남구       2.44
2             경기고등학교   강남구       5.70
3           경기여자고등학교   강남구       5.56
4           서울로봇고등학교   강남구       2.04
..               ...   ...        ...
315  동국대학교사범대학부속고등학교  동대문구       6.05
316       정화여자상업고등학교  동대문구       8.82
317      해성국제컨벤션고등학교  동대문구       3.14
318         해성여자고등학교  동대문구       3.67
319         휘경여자고등학교  동대문구       5.68

[320 rows x 3 columns]

- 위해지표의 지역칼럼을 지우고 점수 칼럼 이름 수정

In [5]:
del Hazard['지역']

In [6]:
Hazard = Hazard.rename({'score_2nd':'Haz_score'},axis=1)

In [7]:
Hazard

           학교코드              학교명       동         위도          경도  Haz_score
0    S010000373           개포고등학교    개포2동  37.484959  127.059405       2.66
1    S010000376         경기여자고등학교    개포2동  37.486887  127.065567       2.66
2    S010000594       수도전기공업고등학교    개포2동  37.484938  127.064480       2.66
3    S010000375           경기고등학교     삼성동  37.517566  127.056074       5.48
4    S010000394           광신고등학교     삼성동  37.464476  126.925939       5.48
..          ...              ...     ...        ...         ...        ...
315  S010000557  한양대학교사범대학부속고등학교     사근동  37.561919  127.042326       2.52
316  S010006382           도선고등학교  왕십리도선동  37.567131  127.026809       6.31
317  S010000436         무학여자고등학교    행당1동  37.556768  127.033599       3.28
318  S010000585         서울방송고등학교     옥수동  37.547773  127.011036       2.46
319  S010000592         성수공업고등학교  성수2가1동  37.540540  127.051298       8.30

[320 rows x 6 columns]

- 위해지표와 취약지표 합치기

In [8]:
Vulnerability_Hazard=pd.merge(Hazard,Vulnerability, how= 'inner', on='학교명')
Vulnerability_Hazard

,학교코드,학교명,동,위도,경도,Haz_score,자치구,Vul_score
0,S010000373,개포고등학교,개포2동,37.484959,127.059405,2.66,강남구,2.44
1,S010000376,경기여자고등학교,개포2동,37.486887,127.065567,2.66,강남구,5.56
2,S010000594,수도전기공업고등학교,개포2동,37.484938,127.064480,2.66,강남구,2.07
3,S010000375,경기고등학교,삼성동,37.517566,127.056074,5.48,강남구,5.70
4,S010000394,광신고등학교,삼성동,37.464476,126.925939,5.48,관악구,3.07
...,...,...,...,...,...,...,...,...
315,S010000557,한양대학교사범대학부속고등학교,사근동,37.561919,127.042326,2.52,성동구,6.68
316,S010006382,도선고등학교,왕십리도선동,37.567131,127.026809,6.31,성동구,2.39
317,S010000436,무학여자고등학교,행당1동,37.556768,127.033599,3.28,성동구,2.76
318,S010000585,서울방송고등학교,옥수동,37.547773,127.011036,2.46,성동구,2.19
319,S010000592,성수공업고등학교,성수2가1동,37.540540,127.051298,8.30,성동구,8.18

In [9]:
Vulnerability_Hazard.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 320 entries, 0 to 319
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   학교코드       320 non-null    object
 1   학교명        320 non-null    object
 2   동          320 non-null    object
 3   위도         320 non-null    float64
 4   경도         320 non-null    float64
 5   Haz_score  320 non-null    float64
 6   자치구        320 non-null    object
 7   Vul_score  320 non-null    float64
dtypes: float64(4), object(4)
memory usage: 22.5+ KB

- 취약점수 + 위해점수

In [10]:
Vulnerability_Hazard['Haz_Vul_score']= Vulnerability_Hazard['Haz_score']+Vulnerability_Hazard['Vul_score']
Vulnerability_Hazard

,학교코드,학교명,동,위도,경도,Haz_score,자치구,Vul_score,Haz_Vul_score
0,S010000373,개포고등학교,개포2동,37.484959,127.059405,2.66,강남구,2.44,5.10
1,S010000376,경기여자고등학교,개포2동,37.486887,127.065567,2.66,강남구,5.56,8.22
2,S010000594,수도전기공업고등학교,개포2동,37.484938,127.064480,2.66,강남구,2.07,4.73
3,S010000375,경기고등학교,삼성동,37.517566,127.056074,5.48,강남구,5.70,11.18
4,S010000394,광신고등학교,삼성동,37.464476,126.925939,5.48,관악구,3.07,8.55
...,...,...,...,...,...,...,...,...,...
315,S010000557,한양대학교사범대학부속고등학교,사근동,37.561919,127.042326,2.52,성동구,6.68,9.20
316,S010006382,도선고등학교,왕십리도선동,37.567131,127.026809,6.31,성동구,2.39,8.70
317,S010000436,무학여자고등학교,행당1동,37.556768,127.033599,3.28,성동구,2.76,6.04
318,S010000585,서울방송고등학교,옥수동,37.547773,127.011036,2.46,성동구,2.19,4.65
319,S010000592,성수공업고등학교,성수2가1동,37.540540,127.051298,8.30,성동구,8.18,16.48

- 내림차순 점수 range 확인

In [11]:
Vulnerability_Hazard.sort_values(by=['Haz_Vul_score'], ascending=[False])

,학교코드,학교명,동,위도,경도,Haz_score,자치구,Vul_score,Haz_Vul_score
192,S010000595,신진과학기술고등학교,응암1동,37.598713,126.918835,9.27,은평구,9.73,19.00
116,S010000629,고명외식고등학교,돈암1동,37.597320,127.020190,9.76,성북구,8.91,18.67
210,S010000644,서일문화예술고등학교,창신3동,37.579380,127.012793,9.52,종로구,9.09,18.61
78,S010000611,영락의료과학고등학교,청룡동,37.476564,126.944783,8.91,관악구,9.45,18.36
177,S010000530,중경고등학교,이촌1동,37.517681,126.975639,8.36,용산구,9.18,17.54
...,...,...,...,...,...,...,...,...,...
208,S010000450,상명대학교사범대학부속여자고등학교,부암동,37.603516,126.953837,2.16,종로구,2.35,4.51
73,S010000448,삼성고등학교,대학동,37.469139,126.943668,2.05,관악구,2.37,4.42
26,S010000453,상일여자고등학교,상일동,37.549220,127.169635,2.24,강동구,2.17,4.41
71,S010000439,미림여자고등학교,대학동,37.466758,126.933272,2.05,관악구,2.33,4.38
72,S010000639,미림여자정보과학고등학교,대학동,37.466336,126.932907,2.05,관악구,2.10,4.15

- 경감지표에서 구 칼럼을 삭제하고 점수 칼럼 수정

In [12]:
del Reduce['구']

In [13]:
Reduce = Reduce.rename({'score_2nd':'Reduce_score'},axis=1)

In [14]:
Reduce

             학교명  Reduce_score
0         영일고등학교         10.00
1       경복여자고등학교         10.00
2       강서공업고등학교         10.00
3     경복비즈니스고등학교         10.00
4         수명고등학교         10.00
..           ...           ...
315       영훈고등학교          0.53
316       문일고등학교          0.35
317     서울예술고등학교          0.21
318  이화여자외국어고등학교          0.11
319     대경상업고등학교          0.11

[320 rows x 2 columns]

- 경감점수를 기존 데이터와 merge

In [15]:
Vulnerability_Hazard_Reduce=pd.merge(Vulnerability_Hazard,Reduce,how='inner',on='학교명')

- 취약점수와 위해점수의 합에 경감점수를 빼기

In [16]:
Vulnerability_Hazard_Reduce['Final_Score'] = Vulnerability_Hazard_Reduce['Haz_Vul_score']-Vulnerability_Hazard_Reduce['Reduce_score']
Vulnerability_Hazard_Reduce

,학교코드,학교명,동,위도,경도,Haz_score,자치구,Vul_score,Haz_Vul_score,Reduce_score,Final_Score
0,S010000373,개포고등학교,개포2동,37.484959,127.059405,2.66,강남구,2.44,5.10,5.37,-0.27
1,S010000376,경기여자고등학교,개포2동,37.486887,127.065567,2.66,강남구,5.56,8.22,5.37,2.85
2,S010000594,수도전기공업고등학교,개포2동,37.484938,127.064480,2.66,강남구,2.07,4.73,3.37,1.36
3,S010000375,경기고등학교,삼성동,37.517566,127.056074,5.48,강남구,5.70,11.18,3.37,7.81
4,S010000394,광신고등학교,삼성동,37.464476,126.925939,5.48,관악구,3.07,8.55,0.59,7.96
...,...,...,...,...,...,...,...,...,...,...,...
315,S010000557,한양대학교사범대학부속고등학교,사근동,37.561919,127.042326,2.52,성동구,6.68,9.20,8.63,0.57
316,S010006382,도선고등학교,왕십리도선동,37.567131,127.026809,6.31,성동구,2.39,8.70,2.63,6.07
317,S010000436,무학여자고등학교,행당1동,37.556768,127.033599,3.28,성동구,2.76,6.04,8.63,-2.59
318,S010000585,서울방송고등학교,옥수동,37.547773,127.011036,2.46,성동구,2.19,4.65,8.63,-3.98
319,S010000592,성수공업고등학교,성수2가1동,37.540540,127.051298,8.30,성동구,8.18,16.48,2.63,13.85

### 상위 20개 학교 확인

In [17]:
top20 = Vulnerability_Hazard_Reduce.sort_values(by=['Final_Score'], ascending=[False]).head(20)
top20

,학교코드,학교명,동,위도,경도,Haz_score,자치구,Vul_score,Haz_Vul_score,Reduce_score,Final_Score
78,S010000611,영락의료과학고등학교,청룡동,37.476564,126.944783,8.91,관악구,9.45,18.36,0.59,17.77
192,S010000595,신진과학기술고등학교,응암1동,37.598713,126.918835,9.27,은평구,9.73,19.00,2.95,16.05
23,S010000568,휘문고등학교,대치2동,37.505109,127.061420,9.82,강남구,6.91,16.73,1.37,15.36
97,S010000582,덕일전자공업고등학교,오류2동,37.490983,126.838799,5.62,구로구,10.00,15.62,1.05,14.57
7,S010000581,단국대학교부속소프트웨어고등학교,대치1동,37.495617,127.057767,6.98,강남구,8.55,15.53,1.37,14.16
116,S010000629,고명외식고등학교,돈암1동,37.597320,127.020190,9.76,성북구,8.91,18.67,4.74,13.93
319,S010000592,성수공업고등학교,성수2가1동,37.540540,127.051298,8.30,성동구,8.18,16.48,2.63,13.85
100,S010005584,서울공연예술고등학교,수궁동,37.500085,126.832152,5.55,구로구,6.96,12.51,1.05,11.46
242,S010005263,불암고등학교,중계본동,37.649158,127.080304,9.39,노원구,5.65,15.04,3.68,11.36
5,S010000631,광신방송예술고등학교,삼성동,37.465719,126.924699,2.48,관악구,9.36,11.84,0.59,11.25
147,S010000642,서울금융고등학교,신월3동,37.537615,126.825664,8.67,양천구,8.36,17.03,5.79,11.24
172,S010000511,용산고등학교,용산2가동,37.545865,126.980328,8.06,용산구,5.59,13.65,2.42,11.23
51,S010000646,서울항공비즈니스고등학교,방화1동,37.569216,126.817042,6.88,강서구,9.91,16.79,6.00,10.79
259,S010000637,서울문화고등학교,방학1동,37.664132,127.047285,6.81,도봉구,9.55,16.36,5.58,10.78
41,S010000486,신일고등학교,미아동,37.628190,127.027724,6.05,강북구,6.95,13.00,2.53,10.47
210,S010000644,서일문화예술고등학교,창신3동,37.579380,127.012793,9.52,종로구,9.09,18.61,8.21,10.40
243,S010000619,영신간호비즈니스고등학교,중계본동,37.652454,127.083277,9.39,노원구,2.62,12.01,1.68,10.33
295,S010000517,이화여자대학교사범대학부속이화금란고등학교,신촌동,37.566366,126.947661,5.12,서대문구,6.57,11.69,1.41,10.28
307,S010000473,세화고등학교,반포2동,37.501952,126.991618,8.79,서초구,6.69,15.48,5.26,10.22
278,S010000378,경문고등학교,사당2동,37.493096,126.981699,5.33,동작구,5.50,10.83,0.82,10.01

In [18]:
top20.reset_index(inplace=True, drop=True)
top20

,학교코드,학교명,동,위도,경도,Haz_score,자치구,Vul_score,Haz_Vul_score,Reduce_score,Final_Score
0,S010000611,영락의료과학고등학교,청룡동,37.476564,126.944783,8.91,관악구,9.45,18.36,0.59,17.77
1,S010000595,신진과학기술고등학교,응암1동,37.598713,126.918835,9.27,은평구,9.73,19.00,2.95,16.05
2,S010000568,휘문고등학교,대치2동,37.505109,127.061420,9.82,강남구,6.91,16.73,1.37,15.36
3,S010000582,덕일전자공업고등학교,오류2동,37.490983,126.838799,5.62,구로구,10.00,15.62,1.05,14.57
4,S010000581,단국대학교부속소프트웨어고등학교,대치1동,37.495617,127.057767,6.98,강남구,8.55,15.53,1.37,14.16
5,S010000629,고명외식고등학교,돈암1동,37.597320,127.020190,9.76,성북구,8.91,18.67,4.74,13.93
6,S010000592,성수공업고등학교,성수2가1동,37.540540,127.051298,8.30,성동구,8.18,16.48,2.63,13.85
7,S010005584,서울공연예술고등학교,수궁동,37.500085,126.832152,5.55,구로구,6.96,12.51,1.05,11.46
8,S010005263,불암고등학교,중계본동,37.649158,127.080304,9.39,노원구,5.65,15.04,3.68,11.36
9,S010000631,광신방송예술고등학교,삼성동,37.465719,126.924699,2.48,관악구,9.36,11.84,0.59,11.25
10,S010000642,서울금융고등학교,신월3동,37.537615,126.825664,8.67,양천구,8.36,17.03,5.79,11.24
11,S010000511,용산고등학교,용산2가동,37.545865,126.980328,8.06,용산구,5.59,13.65,2.42,11.23
12,S010000646,서울항공비즈니스고등학교,방화1동,37.569216,126.817042,6.88,강서구,9.91,16.79,6.00,10.79
13,S010000637,서울문화고등학교,방학1동,37.664132,127.047285,6.81,도봉구,9.55,16.36,5.58,10.78
14,S010000486,신일고등학교,미아동,37.628190,127.027724,6.05,강북구,6.95,13.00,2.53,10.47
15,S010000644,서일문화예술고등학교,창신3동,37.579380,127.012793,9.52,종로구,9.09,18.61,8.21,10.40
16,S010000619,영신간호비즈니스고등학교,중계본동,37.652454,127.083277,9.39,노원구,2.62,12.01,1.68,10.33
17,S010000517,이화여자대학교사범대학부속이화금란고등학교,신촌동,37.566366,126.947661,5.12,서대문구,6.57,11.69,1.41,10.28
18,S010000473,세화고등학교,반포2동,37.501952,126.991618,8.79,서초구,6.69,15.48,5.26,10.22
19,S010000378,경문고등학교,사당2동,37.493096,126.981699,5.33,동작구,5.50,10.83,0.82,10.01

In [19]:
top30 = Vulnerability_Hazard_Reduce.sort_values(by=['Final_Score'], ascending=[False]).head(30)
top30

,학교코드,학교명,동,위도,경도,Haz_score,자치구,Vul_score,Haz_Vul_score,Reduce_score,Final_Score
78,S010000611,영락의료과학고등학교,청룡동,37.476564,126.944783,8.91,관악구,9.45,18.36,0.59,17.77
192,S010000595,신진과학기술고등학교,응암1동,37.598713,126.918835,9.27,은평구,9.73,19.00,2.95,16.05
23,S010000568,휘문고등학교,대치2동,37.505109,127.061420,9.82,강남구,6.91,16.73,1.37,15.36
97,S010000582,덕일전자공업고등학교,오류2동,37.490983,126.838799,5.62,구로구,10.00,15.62,1.05,14.57
7,S010000581,단국대학교부속소프트웨어고등학교,대치1동,37.495617,127.057767,6.98,강남구,8.55,15.53,1.37,14.16
116,S010000629,고명외식고등학교,돈암1동,37.597320,127.020190,9.76,성북구,8.91,18.67,4.74,13.93
319,S010000592,성수공업고등학교,성수2가1동,37.540540,127.051298,8.30,성동구,8.18,16.48,2.63,13.85
100,S010005584,서울공연예술고등학교,수궁동,37.500085,126.832152,5.55,구로구,6.96,12.51,1.05,11.46
242,S010005263,불암고등학교,중계본동,37.649158,127.080304,9.39,노원구,5.65,15.04,3.68,11.36
5,S010000631,광신방송예술고등학교,삼성동,37.465719,126.924699,2.48,관악구,9.36,11.84,0.59,11.25
147,S010000642,서울금융고등학교,신월3동,37.537615,126.825664,8.67,양천구,8.36,17.03,5.79,11.24
172,S010000511,용산고등학교,용산2가동,37.545865,126.980328,8.06,용산구,5.59,13.65,2.42,11.23
51,S010000646,서울항공비즈니스고등학교,방화1동,37.569216,126.817042,6.88,강서구,9.91,16.79,6.00,10.79
259,S010000637,서울문화고등학교,방학1동,37.664132,127.047285,6.81,도봉구,9.55,16.36,5.58,10.78
41,S010000486,신일고등학교,미아동,37.628190,127.027724,6.05,강북구,6.95,13.00,2.53,10.47
210,S010000644,서일문화예술고등학교,창신3동,37.579380,127.012793,9.52,종로구,9.09,18.61,8.21,10.40
243,S010000619,영신간호비즈니스고등학교,중계본동,37.652454,127.083277,9.39,노원구,2.62,12.01,1.68,10.33
295,S010000517,이화여자대학교사범대학부속이화금란고등학교,신촌동,37.566366,126.947661,5.12,서대문구,6.57,11.69,1.41,10.28
307,S010000473,세화고등학교,반포2동,37.501952,126.991618,8.79,서초구,6.69,15.48,5.26,10.22
278,S010000378,경문고등학교,사당2동,37.493096,126.981699,5.33,동작구,5.50,10.83,0.82,10.01
92,S010000383,경인고등학교,고척1동,37.495994,126.865431,9.21,구로구,5.81,15.02,5.05,9.97
246,S010000454,서라벌고등학교,중계1동,37.645242,127.075837,7.00,노원구,6.59,13.59,3.68,9.91
18,S010000495,영동고등학교,청담동,37.520183,127.043348,5.71,강남구,5.38,11.09,1.37,9.72
130,S010005182,방산고등학교,방이1동,37.508400,127.120472,9.94,송파구,5.29,15.23,5.89,9.34
32,S010000423,동북고등학교,둔촌1동,37.519719,127.141223,5.02,강동구,5.72,10.74,1.47,9.27
177,S010000530,중경고등학교,이촌1동,37.517681,126.975639,8.36,용산구,9.18,17.54,8.42,9.12
275,S010000602,휘경공업고등학교,전농2동,37.585220,127.069729,9.33,동대문구,8.09,17.42,8.32,9.10
21,S010000538,진선여자고등학교,역삼2동,37.501828,127.046904,3.94,강남구,6.46,10.40,1.37,9.03
42,S010000505,영훈고등학교,미아동,37.613509,127.027784,3.05,강북구,6.42,9.47,0.53,8.94
178,S010000408,대성고등학교,갈현2동,37.623170,126.909361,3.70,은평구,6.17,9.87,0.95,8.92

In [20]:
top30.reset_index(inplace=True, drop=True)
top30

,학교코드,학교명,동,위도,경도,Haz_score,자치구,Vul_score,Haz_Vul_score,Reduce_score,Final_Score
0,S010000611,영락의료과학고등학교,청룡동,37.476564,126.944783,8.91,관악구,9.45,18.36,0.59,17.77
1,S010000595,신진과학기술고등학교,응암1동,37.598713,126.918835,9.27,은평구,9.73,19.00,2.95,16.05
2,S010000568,휘문고등학교,대치2동,37.505109,127.061420,9.82,강남구,6.91,16.73,1.37,15.36
3,S010000582,덕일전자공업고등학교,오류2동,37.490983,126.838799,5.62,구로구,10.00,15.62,1.05,14.57
4,S010000581,단국대학교부속소프트웨어고등학교,대치1동,37.495617,127.057767,6.98,강남구,8.55,15.53,1.37,14.16
5,S010000629,고명외식고등학교,돈암1동,37.597320,127.020190,9.76,성북구,8.91,18.67,4.74,13.93
6,S010000592,성수공업고등학교,성수2가1동,37.540540,127.051298,8.30,성동구,8.18,16.48,2.63,13.85
7,S010005584,서울공연예술고등학교,수궁동,37.500085,126.832152,5.55,구로구,6.96,12.51,1.05,11.46
8,S010005263,불암고등학교,중계본동,37.649158,127.080304,9.39,노원구,5.65,15.04,3.68,11.36
9,S010000631,광신방송예술고등학교,삼성동,37.465719,126.924699,2.48,관악구,9.36,11.84,0.59,11.25
10,S010000642,서울금융고등학교,신월3동,37.537615,126.825664,8.67,양천구,8.36,17.03,5.79,11.24
11,S010000511,용산고등학교,용산2가동,37.545865,126.980328,8.06,용산구,5.59,13.65,2.42,11.23
12,S010000646,서울항공비즈니스고등학교,방화1동,37.569216,126.817042,6.88,강서구,9.91,16.79,6.00,10.79
13,S010000637,서울문화고등학교,방학1동,37.664132,127.047285,6.81,도봉구,9.55,16.36,5.58,10.78
14,S010000486,신일고등학교,미아동,37.628190,127.027724,6.05,강북구,6.95,13.00,2.53,10.47
15,S010000644,서일문화예술고등학교,창신3동,37.579380,127.012793,9.52,종로구,9.09,18.61,8.21,10.40
16,S010000619,영신간호비즈니스고등학교,중계본동,37.652454,127.083277,9.39,노원구,2.62,12.01,1.68,10.33
17,S010000517,이화여자대학교사범대학부속이화금란고등학교,신촌동,37.566366,126.947661,5.12,서대문구,6.57,11.69,1.41,10.28
18,S010000473,세화고등학교,반포2동,37.501952,126.991618,8.79,서초구,6.69,15.48,5.26,10.22
19,S010000378,경문고등학교,사당2동,37.493096,126.981699,5.33,동작구,5.50,10.83,0.82,10.01
20,S010000383,경인고등학교,고척1동,37.495994,126.865431,9.21,구로구,5.81,15.02,5.05,9.97
21,S010000454,서라벌고등학교,중계1동,37.645242,127.075837,7.00,노원구,6.59,13.59,3.68,9.91
22,S010000495,영동고등학교,청담동,37.520183,127.043348,5.71,강남구,5.38,11.09,1.37,9.72
23,S010005182,방산고등학교,방이1동,37.508400,127.120472,9.94,송파구,5.29,15.23,5.89,9.34
24,S010000423,동북고등학교,둔촌1동,37.519719,127.141223,5.02,강동구,5.72,10.74,1.47,9.27
25,S010000530,중경고등학교,이촌1동,37.517681,126.975639,8.36,용산구,9.18,17.54,8.42,9.12
26,S010000602,휘경공업고등학교,전농2동,37.585220,127.069729,9.33,동대문구,8.09,17.42,8.32,9.10
27,S010000538,진선여자고등학교,역삼2동,37.501828,127.046904,3.94,강남구,6.46,10.40,1.37,9.03
28,S010000505,영훈고등학교,미아동,37.613509,127.027784,3.05,강북구,6.42,9.47,0.53,8.94
29,S010000408,대성고등학교,갈현2동,37.623170,126.909361,3.70,은평구,6.17,9.87,0.95,8.92

In [35]:
Violence_Score20 = top20[['학교명','Final_Score','위도','경도']]
Violence_Score20

                      학교명  Final_Score         위도          경도
0              영락의료과학고등학교        17.77  37.476564  126.944783
1              신진과학기술고등학교        16.05  37.598713  126.918835
2                  휘문고등학교        15.36  37.505109  127.061420
3              덕일전자공업고등학교        14.57  37.490983  126.838799
4        단국대학교부속소프트웨어고등학교        14.16  37.495617  127.057767
5                고명외식고등학교        13.93  37.597320  127.020190
6                성수공업고등학교        13.85  37.540540  127.051298
7              서울공연예술고등학교        11.46  37.500085  126.832152
8                  불암고등학교        11.36  37.649158  127.080304
9              광신방송예술고등학교        11.25  37.465719  126.924699
10               서울금융고등학교        11.24  37.537615  126.825664
11                 용산고등학교        11.23  37.545865  126.980328
12           서울항공비즈니스고등학교        10.79  37.569216  126.817042
13               서울문화고등학교        10.78  37.664132  127.047285
14                 신일고등학교        10.47  37.628190  127.027724
15             서일문화예술고등학교        10.40  37.579380  127.012793
16           영신간호비즈니스고등학교        10.33  37.652454  127.083277
17  이화여자대학교사범대학부속이화금란고등학교        10.28  37.566366  126.947661
18                 세화고등학교        10.22  37.501952  126.991618
19                 경문고등학교        10.01  37.493096  126.981699

In [21]:
Violence_Score20 = top20[['학교명','Final_Score','동','위도','경도']]
Violence_Score20

                      학교명  Final_Score       동         위도          경도
0              영락의료과학고등학교        17.77     청룡동  37.476564  126.944783
1              신진과학기술고등학교        16.05    응암1동  37.598713  126.918835
2                  휘문고등학교        15.36    대치2동  37.505109  127.061420
3              덕일전자공업고등학교        14.57    오류2동  37.490983  126.838799
4        단국대학교부속소프트웨어고등학교        14.16    대치1동  37.495617  127.057767
5                고명외식고등학교        13.93    돈암1동  37.597320  127.020190
6                성수공업고등학교        13.85  성수2가1동  37.540540  127.051298
7              서울공연예술고등학교        11.46     수궁동  37.500085  126.832152
8                  불암고등학교        11.36    중계본동  37.649158  127.080304
9              광신방송예술고등학교        11.25     삼성동  37.465719  126.924699
10               서울금융고등학교        11.24    신월3동  37.537615  126.825664
11                 용산고등학교        11.23   용산2가동  37.545865  126.980328
12           서울항공비즈니스고등학교        10.79    방화1동  37.569216  126.817042
13               서울문화고등학교        10.78    방학1동  37.664132  127.047285
14                 신일고등학교        10.47     미아동  37.628190  127.027724
15             서일문화예술고등학교        10.40    창신3동  37.579380  127.012793
16           영신간호비즈니스고등학교        10.33    중계본동  37.652454  127.083277
17  이화여자대학교사범대학부속이화금란고등학교        10.28     신촌동  37.566366  126.947661
18                 세화고등학교        10.22    반포2동  37.501952  126.991618
19                 경문고등학교        10.01    사당2동  37.493096  126.981699

In [32]:
Violence_Score30 = top30[['학교명','동','Final_Score','위도','경도']]
Violence_Score30

                      학교명       동  Final_Score         위도          경도
0              영락의료과학고등학교     청룡동        17.77  37.476564  126.944783
1              신진과학기술고등학교    응암1동        16.05  37.598713  126.918835
2                  휘문고등학교    대치2동        15.36  37.505109  127.061420
3              덕일전자공업고등학교    오류2동        14.57  37.490983  126.838799
4        단국대학교부속소프트웨어고등학교    대치1동        14.16  37.495617  127.057767
5                고명외식고등학교    돈암1동        13.93  37.597320  127.020190
6                성수공업고등학교  성수2가1동        13.85  37.540540  127.051298
7              서울공연예술고등학교     수궁동        11.46  37.500085  126.832152
8                  불암고등학교    중계본동        11.36  37.649158  127.080304
9              광신방송예술고등학교     삼성동        11.25  37.465719  126.924699
10               서울금융고등학교    신월3동        11.24  37.537615  126.825664
11                 용산고등학교   용산2가동        11.23  37.545865  126.980328
12           서울항공비즈니스고등학교    방화1동        10.79  37.569216  126.817042
13               서울문화고등학교    방학1동        10.78  37.664132  127.047285
14                 신일고등학교     미아동        10.47  37.628190  127.027724
15             서일문화예술고등학교    창신3동        10.40  37.579380  127.012793
16           영신간호비즈니스고등학교    중계본동        10.33  37.652454  127.083277
17  이화여자대학교사범대학부속이화금란고등학교     신촌동        10.28  37.566366  126.947661
18                 세화고등학교    반포2동        10.22  37.501952  126.991618
19                 경문고등학교    사당2동        10.01  37.493096  126.981699
20                 경인고등학교    고척1동         9.97  37.495994  126.865431
21                서라벌고등학교    중계1동         9.91  37.645242  127.075837
22                 영동고등학교     청담동         9.72  37.520183  127.043348
23                 방산고등학교    방이1동         9.34  37.508400  127.120472
24                 동북고등학교    둔촌1동         9.27  37.519719  127.141223
25                 중경고등학교    이촌1동         9.12  37.517681  126.975639
26               휘경공업고등학교    전농2동         9.10  37.585220  127.069729
27               진선여자고등학교    역삼2동         9.03  37.501828  127.046904
28                 영훈고등학교     미아동         8.94  37.613509  127.027784
29                 대성고등학교    갈현2동         8.92  37.623170  126.909361

In [36]:
Violence_Score20.to_csv('data/Violence_Score20.csv',index=False)