# 경감지표

In [1]:
import pandas as pd
import numpy as np

## 학교별 상담소 관련 데이터

In [2]:
Wee = pd.read_excel('서울시고등학교_교육여건_상담.xlsx')
Wee

,구,학교명,학교코드,내부상담_실시여부,외부상담_실시여부,wee클래스_운영여부,학교폭력_예방교육_평균교육시간(1학급당)
0,강남구,개포고등학교,S010000373,1,1,1,382.4
1,강남구,경기고등학교,S010000375,1,0,1,152.4
2,강남구,경기여자고등학교,S010000376,1,1,1,200.0
3,강남구,국립국악고등학교,S000003540,0,0,0,217.4
4,강남구,단국대학교부속소프트웨어고등학교,S010000581,0,1,0,300.0
...,...,...,...,...,...,...,...
315,성동구,무학여자고등학교,S010000436,1,1,1,253.3
316,성동구,서울방송고등학교,S010000585,1,1,1,87.6
317,성동구,성수고등학교,S010005523,1,1,1,406.6
318,성동구,성수공업고등학교,S010000592,1,0,1,306.5
319,성동구,한양대학교사범대학부속고등학교,S010000557,1,1,1,137.0

## 구별 CCTV 대수 데이터

In [3]:
CCTV = pd.read_csv('서울시 CCTV 설치운영 현황(자치구)-목적별.csv',encoding='cp949', thousands = ',')
CCTV

,구분,총계,방범,어린이\n보호구역,공원·놀이터,쓰레기\n무단투기,시설안전·화재예방,교통단속,교통정보수집·분석,기타다른법령
0,종로구,1729,1360,41,109,0,110,109,0,0
1,중구,2001,1180,75,165,62,62,290,8,159
2,용산구,2383,1740,164,154,0,0,252,0,73
3,성동구,3515,2834,0,177,151,15,338,0,0
4,광진구,2556,2011,301,98,71,5,70,0,0
5,동대문,2315,1682,282,174,28,1,134,0,14
6,중랑구,3285,2872,141,141,11,54,66,0,0
7,성북구,3754,2489,400,192,359,108,183,23,0
8,강북구,2462,1831,319,187,0,32,93,0,0
9,도봉구,1356,747,188,135,119,77,90,0,0
10,노원구,2282,1245,260,402,127,111,137,0,0
11,은평구,3660,2335,697,399,0,123,106,0,0
12,서대문,2939,1846,132,521,0,91,317,0,32
13,마포구,2401,1918,192,158,0,0,133,0,0
14,양천구,3307,2103,768,265,0,0,171,0,0
15,강서구,2437,1949,215,155,27,0,91,0,0
16,구로구,4075,2501,540,384,30,119,257,0,244
17,금천구,2365,1758,271,174,44,0,118,0,0
18,영등포,3773,2758,264,175,53,7,516,0,0
19,동작구,2262,1615,394,127,19,59,43,0,5
20,관악구,4909,3226,417,282,157,642,185,0,0
21,서초구,3730,2232,332,170,0,215,781,0,0
22,강남구,6645,4525,775,496,0,104,593,0,152
23,송파구,2743,1518,311,543,0,77,294,0,0
24,강동구,2547,2084,232,159,0,0,72,0,0

In [4]:
CCTV = CCTV[['구분','방범','어린이\n보호구역']]
CCTV.head()

    구분    방범  어린이\n보호구역
0  종로구  1360         41
1   중구  1180         75
2  용산구  1740        164
3  성동구  2834          0
4  광진구  2011        301

In [5]:
CCTV = CCTV.rename({'구분':'구','방범':'방범용CCTV','어린이\n보호구역':'어린이보호구역CCTV'},axis=1)
CCTV

      구  방범용CCTV  어린이보호구역CCTV
0   종로구     1360           41
1    중구     1180           75
2   용산구     1740          164
3   성동구     2834            0
4   광진구     2011          301
5   동대문     1682          282
6   중랑구     2872          141
7   성북구     2489          400
8   강북구     1831          319
9   도봉구      747          188
10  노원구     1245          260
11  은평구     2335          697
12  서대문     1846          132
13  마포구     1918          192
14  양천구     2103          768
15  강서구     1949          215
16  구로구     2501          540
17  금천구     1758          271
18  영등포     2758          264
19  동작구     1615          394
20  관악구     3226          417
21  서초구     2232          332
22  강남구     4525          775
23  송파구     1518          311
24  강동구     2084          232

In [6]:
CCTV.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   구            25 non-null     object
 1   방범용CCTV      25 non-null     int64
 2   어린이보호구역CCTV  25 non-null     int64
dtypes: int64(2), object(1)
memory usage: 728.0+ bytes

- 두 데이터셋 merge

In [7]:
data_reduce = pd.merge(Wee,CCTV,on='구',how='inner')
data_reduce.head()

,구,학교명,학교코드,내부상담_실시여부,외부상담_실시여부,wee클래스_운영여부,학교폭력_예방교육_평균교육시간(1학급당),방범용CCTV,어린이보호구역CCTV
0,강남구,개포고등학교,S010000373,1,1,1,382.4,4525,775
1,강남구,경기고등학교,S010000375,1,0,1,152.4,4525,775
2,강남구,경기여자고등학교,S010000376,1,1,1,200.0,4525,775
3,강남구,국립국악고등학교,S000003540,0,0,0,217.4,4525,775
4,강남구,단국대학교부속소프트웨어고등학교,S010000581,0,1,0,300.0,4525,775

### 파출소 위치 데이터 & 학교 위치데이터 확인

In [8]:
Police_station = pd.read_csv('경찰청_경찰관서 위치.csv',encoding='cp949')
Police_station

       청        서   지구대파출소         X좌표        Y좌표
0    서울청  서울강남경찰서   논현1파출소  127.029316  37.513791
1    서울청  서울강남경찰서   논현2파출소  127.033875  37.515220
2    서울청  서울강남경찰서   삼성1파출소  127.060440  37.514852
3    서울청  서울강남경찰서   삼성2파출소  127.048063  37.511289
4    서울청  서울강남경찰서  서울강남경찰서  127.067177  37.509036
..   ...      ...      ...         ...        ...
269  서울청  서울혜화경찰서  종로5가파출소  127.001606  37.570727
270  서울청  서울혜화경찰서    창신파출소  127.013702  37.578482
271  서울청  서울혜화경찰서    혜화파출소  127.001422  37.586135
272  서울청  서울혜화경찰서    효제파출소  127.003606  37.574259
273  서울청      서울청      서울청  126.972072  37.575060

[274 rows x 5 columns]

In [9]:
학교좌표 = pd.read_csv('학교위치_수정.csv', encoding = 'cp949')
학교좌표

,지역,학교명,위도,경도,남녀공학,학생수.x,위도중심,경도중심,distance,학생수가중치,승하차인원,학생수.y,학생수.y_sc,승하차인원_sc,distance_sc,func
0,종로구,경신고등학교,37.592173,127.000227,남,645,37.591417,127.000587,0.000838,613,20839569,2413602,1.00000,0.51102,0.02860,17.86783
1,종로구,서울과학고등학교,37.591557,126.998469,남녀공학,376,37.591417,127.000587,0.002123,376,20839569,2413602,1.00000,0.51102,0.07249,7.04952
2,종로구,서울국제고등학교,37.591342,126.993789,남녀공학,450,37.591417,127.000587,0.006798,450,20839569,2413602,1.00000,0.51102,0.23213,2.20144
3,종로구,동성고등학교,37.584970,127.003098,남,857,37.591417,127.000587,0.006918,814,20839569,2413602,1.00000,0.51102,0.23622,2.16332
4,종로구,중앙고등학교,37.584027,126.986877,남,975,37.591417,127.000587,0.015575,926,20839569,2413602,1.00000,0.51102,0.53181,0.96091
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316,양천구,신목고등학교,37.512763,126.873615,남녀공학,1188,37.508748,126.856750,0.017337,1188,4496252,78040,0.03210,0.00000,0.59198,0.00000
317,양천구,대일관광고등학교,37.613956,127.012925,녀,530,37.630750,127.018773,0.017783,477,4496252,171810,0.07096,0.00000,0.60720,0.00000
318,양천구,진명여자고등학교,37.524048,126.865855,녀,1388,37.508748,126.856750,0.017804,1249,4496252,78040,0.03210,0.00000,0.60795,0.00000
319,양천구,강서고등학교,37.536777,126.866330,남,971,37.553703,126.856645,0.019501,922,4496252,22738,0.00918,0.00000,0.66587,0.00000
320,양천구,신서고등학교,37.500000,126.800000,남녀공학,576,37.496914,126.822986,0.023192,576,4496252,40054,0.01635,0.00000,0.79191,0.00000

In [10]:
학교좌표.groupby('지역').count()

,학교명,위도,경도,남녀공학,학생수.x,위도중심,경도중심,distance,학생수가중치,승하차인원,학생수.y,학생수.y_sc,승하차인원_sc,distance_sc,func
지역,,,,,,,,,,,,,,,
강남구,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22
강동구,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14
강북구,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
강서구,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23
관악구,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
광진구,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
구로구,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14
금천구,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
노원구,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25
도봉구,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
동대문구,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11
동작구,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
마포구,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
서대문구,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
서초구,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11
성동구,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
성북구,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13
송파구,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19
양천구,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15
영등포구,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
용산구,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11
은평구,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18
종로구,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14
중구,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11
중랑구,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10

In [12]:
data_reduce.isnull().sum()

구                         0
학교명                       0
학교코드                      0
내부상담_실시여부                 0
외부상담_실시여부                 0
wee클래스_운영여부               0
학교폭력_예방교육_평균교육시간(1학급당)    0
방범용CCTV                   0
어린이보호구역CCTV               0
dtype: int64

In [13]:
학교좌표.isnull().sum()

지역             0
학교명            0
위도             0
경도             0
남녀공학           0
학생수.x          0
위도중심           0
경도중심           0
distance       0
학생수가중치         0
승하차인원          0
학생수.y          0
학생수.y_sc       0
승하차인원_sc       0
distance_sc    0
func           0
dtype: int64